import os
import re

file_path = r"c:\workspace\Jollibee\index.html"

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    "Jollibee - Supper delicious Burger in town!": "Jollibee - Bánh Burger siêu ngon trong thành phố!",
    ">Home<": ">Trang chủ<",
    ">About Us<": ">Về chúng tôi<",
    ">Shop<": ">Cửa hàng<",
    ">Blog<": ">Bài viết<",
    ">Contact Us<": ">Liên hệ<",
    ">Reservation<": ">Đặt bàn<",
    "Type keywords here...": "Nhập từ khóa tại đây...",
    ">Eat Sleep And<": ">Ăn, Ngủ Và<",
    ">Supper delicious Burger in town!<": ">Bánh Burger siêu ngon trong thành phố!<",
    ">Thức ăn là bất kỳ chất nào được tiêu thụ để cung cấp hỗ trợ dinh dưỡng cho một sinh vật<": ">Thực phẩm là nguồn cung cấp dinh dưỡng thiết yếu cho cơ thể.<",
    "Food is any substance consumed to provide nutritional\n            support for an organism.": "Thực phẩm là nguồn cung cấp dinh dưỡng thiết yếu cho cơ thể.",
    ">Book A Table<": ">Đặt Bàn<",
    ">Maxican Pizza<": ">Pizza Mexico<",
    ">Soft Drinks<": ">Nước Ngọt<",
    ">French Fry<": ">Khoai Tây Chiên<",
    ">Burger Kingo<": ">Burger Kingo<",
    ">Chicken Masala<": ">Gà Masala<",
    "Caferio, Burgers, and Best Pizzas\n              <span class=\"span\">in Town!</span>": "Caferio, Burgers và Pizza ngon nhất\n              <span class=\"span\">thành phố!</span>",
    "The restaurants in Hangzhou also catered to many northern Chinese who had fled south from Kaifeng during\n              the Jurchen\n              invasion of the 1120s, while it is also known that many restaurants were run by families.": "Các nhà hàng của chúng tôi cung cấp những món ăn ngon nhất với công thức đặc biệt, mang lại trải nghiệm tuyệt vời cho gia đình và bạn bè.",
    ">Delicious & Healthy Foods<": ">Món Ăn Ngon & Khỏe<",
    ">Spacific Family And Kids Zone<": ">Khu Vực Dành Riêng Cho Gia Đình & Trẻ Em<",
    ">Music & Other Facilities<": ">Âm Nhạc & Tiện Ích Khác<",
    ">Fastest Food Home Delivery<": ">Giao Hàng Tận Nơi Nhanh Nhất<",
    ">Order Now<": ">Đặt Hàng Ngay<",
    ">Popular Dishes<": ">Món Phổ Biến<",
    "Our Delicious <span class=\"span\">Foods</span>": "Những Món Ăn <span class=\"span\">Ngon Tuyệt</span>",
    ">All<": ">Tất cả<",
    ">Pizza<": ">Pizza<",
    ">Burger<": ">Burger<",
    ">Drinks<": ">Đồ uống<",
    ">Sandwich<": ">Sandwich<",
    ">Fried Chicken Unlimited<": ">Gà Rán Không Giới Hạn<",
    ">Price:<": ">Giá:<",
    ">Chicken<": ">Gà<",
    ">Noddles<": ">Mì<",
    ">Burger King Whopper<": ">Burger King Whopper<",
    ">Pizzas<": ">Pizza<",
    ">White Castle Pizzas<": ">Pizza White Castle<",
    ">Burrito<": ">Burrito<",
    ">Bell Burrito Supreme<": ">Bell Burrito Supreme<",
    ">Nuggets<": ">Gà Viên<",
    ">Kung Pao Chicken BBQ<": ">Gà BBQ Kung Pao<",
    ">Wendy's Chicken<": ">Gà Wendy's<",
    "The Jollibee Have Excellent Of\n              <span class=\"span\">Quality Burgers!</span>": "Jollibee Mang Đến Những Chiếc\n              <span class=\"span\">Burger Chất Lượng Nhất!</span>",
    "A Moments Of Delivered On <span class=\"span\">Right Time</span> & Place": "Giao Hàng Đúng <span class=\"span\">Thời Gian</span> & Địa Điểm",
    ">Testimonials<": ">Đánh Giá<",
    "Our Customers <span class=\"span\">Reviews</span>": "Khách Hàng <span class=\"span\">Nhận Xét</span>",
    '"I would be lost without restaurant. I would like to personally thank you for your outstanding\n                  product."': '"Tôi sẽ không biết ăn ở đâu nếu thiếu nhà hàng này. Cá nhân tôi muốn cảm ơn vì sản phẩm tuyệt vời của các bạn."',
    ">Discount For Delicious Tasty Burgers!<": ">Giảm Giá Cho Burger Thơm Ngon!<",
    ">50% Off Now!<": ">Giảm Ngay 50%!<",
    ">Sale off 50% only this week<": ">Giảm 50% duy nhất tuần này<",
    ">Delicious Pizza<": ">Pizza Ngon Hảo Hạng<",
    ">50% off Now<": ">Giảm ngay 50%<",
    ">American Burgers<": ">Burger Kiểu Mỹ<",
    ">Tasty Buzzed Pizza<": ">Pizza Hương Vị Đậm Đà<",
    ">Latest Blog Posts<": ">Bài Viết Mới Nhất<",
    "This Is All About <span class=\"span\">Foods</span>": "Tất Cả Về <span class=\"span\">Ẩm Thực</span>",
    ">What Do You Think About Cheese Pizza Recipes?<": ">Bạn Nghĩ Gì Về Công Thức Pizza Phô Mai?<",
    ">Jan 01 2022<": ">01 Thg 1, 2022<",
    ">..<": ">Khám phá những công thức tuyệt vời và những câu chuyện thú vị đằng sau mỗi món ăn ngon...<",
    "><": ">Khám phá những công thức tuyệt vời và những câu chuyện thú vị đằng sau mỗi món ăn ngon.<",
    ">Read More<": ">Xem Thêm<",
    ">Making Chicken Strips With New Delicious Ingridents.<": ">Làm Gà Rán Với Nguyên Liệu Mới Thơm Ngon.<",
    ">Innovative Hot Chessyraw Pasta Make Creator Fact.<": ">Sự Thật Về Cách Làm Pasta Phô Mai Nóng Sốt Sáng Tạo.<",
    ">Contact Info<": ">Thông Tin Liên Hệ<",
    ">Opening Hours<": ">Giờ Mở Cửa<",
    ">Monday-Friday: 08:00-22:00<": ">Thứ 2 - Thứ 6: 08:00-22:00<",
    ">Tuesday 4PM: Till Mid Night<": ">Thứ 3 4PM: Đến Nửa Đêm<",
    ">Saturday: 10:00-16:00<": ">Thứ 7: 10:00-16:00<",
    ">Book a table<": ">Đặt bàn<",
    ">Book a Table<": ">Đặt Bàn<",
    'placeholder="Your Name"': 'placeholder="Tên của bạn"',
    'aria-label="Your Name"': 'aria-label="Tên của bạn"',
    'placeholder="Email"': 'placeholder="Email"',
    'aria-label="Email"': 'aria-label="Email"',
    '>Person<': '>Số người<',
    '>2 Person<': '>2 Người<',
    '>3 Person<': '>3 Người<',
    '>4 Person<': '>4 Người<',
    '>5 Person<': '>5 Người<',
    'placeholder="Message"': 'placeholder="Tin nhắn"',
    'aria-label="Message"': 'aria-label="Tin nhắn"',
    'All Rights Reserved.': 'Bảo lưu Mọi Quyền.',
    'alt="Fried Chicken Unlimited"': 'alt="Gà Rán Không Giới Hạn"',
    'alt="Burger King Whopper"': 'alt="Burger King Whopper"',
    'alt="White Castle Pizzas"': 'alt="Pizza White Castle"',
    'alt="Bell Burrito Supreme"': 'alt="Bell Burrito Supreme"',
    'alt="Kung Pao Chicken BBQ"': 'alt="Gà BBQ Kung Pao"',
    "alt=\"Wendy's Chicken\"": "alt=\"Gà Wendy's\""
}

for eng, vie in replacements.items():
    content = content.replace(eng, vie)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Translation completed.")
